// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UltimateShoppingList;

namespace UltimateShoppingList.Migrations
{
    [DbContext(typeof(ShoppingListContext))]
    [Migration("20200228231122_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UltimateShoppingList.Activity", b =>
                {
                    b.Property<int>("ActivityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ActivityDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("ActivityDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActivityShoppingListID")
                        .HasColumnType("int");

                    b.Property<int>("ActivityUserID")
                        .HasColumnType("int");

                    b.Property<int?>("GroupsGroupID")
                        .HasColumnType("int");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ActivityID")
                        .HasName("PK_Activities");

                    b.HasIndex("ActivityShoppingListID");

                    b.HasIndex("GroupsGroupID");

                    b.HasIndex("ProductID");

                    b.HasIndex("UserID");

                    b.ToTable("ActivitiesTable");
                });

            modelBuilder.Entity("UltimateShoppingList.Groups", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("GroupCategory")
                        .HasColumnType("int");

                    b.Property<int>("GroupCreatedByUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("GroupCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupID")
                        .HasName("PK_Groups");

                    b.HasIndex("GroupCreatedByUser");

                    b.ToTable("GroupsTable");
                });

            modelBuilder.Entity("UltimateShoppingList.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProductCategory")
                        .HasColumnType("int");

                    b.Property<int?>("ProductCreatedByUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProductCreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ProductPickedUp")
                        .HasColumnType("bit");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("ProductSharedWithGroupID")
                        .HasColumnType("int");

                    b.Property<int>("ShoppingListID")
                        .HasColumnType("int");

                    b.Property<int?>("ShoppingListShopListID")
                        .HasColumnType("int");

                    b.HasKey("ProductID")
                        .HasName("PK_Products");

                    b.HasIndex("ProductCreatedByUserID");

                    b.HasIndex("ProductSharedWithGroupID");

                    b.HasIndex("ShoppingListID");

                    b.HasIndex("ShoppingListShopListID");

                    b.ToTable("ProductsTable");
                });

            modelBuilder.Entity("UltimateShoppingList.ShoppingList", b =>
                {
                    b.Property<int>("ShopListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ShopListCreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShopListEmailAddressOfOwner")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("ShopListName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShopListUsersGroupID")
                        .HasColumnType("int");

                    b.HasKey("ShopListID")
                        .HasName("PK_ShoppingLists");

                    b.HasIndex("ShopListUsersGroupID");

                    b.ToTable("ShoppingListsTable");
                });

            modelBuilder.Entity("UltimateShoppingList.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GroupsGroupID")
                        .HasColumnType("int");

                    b.Property<string>("UserAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID")
                        .HasName("PK_Users");

                    b.HasIndex("GroupsGroupID");

                    b.ToTable("UsersTable");
                });

            modelBuilder.Entity("UltimateShoppingList.Activity", b =>
                {
                    b.HasOne("UltimateShoppingList.ShoppingList", "ShoppingList")
                        .WithMany()
                        .HasForeignKey("ActivityShoppingListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UltimateShoppingList.Groups", "Groups")
                        .WithMany()
                        .HasForeignKey("GroupsGroupID");

                    b.HasOne("UltimateShoppingList.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID");

                    b.HasOne("UltimateShoppingList.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("UltimateShoppingList.Groups", b =>
                {
                    b.HasOne("UltimateShoppingList.User", "User")
                        .WithMany()
                        .HasForeignKey("GroupCreatedByUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UltimateShoppingList.Product", b =>
                {
                    b.HasOne("UltimateShoppingList.User", "ProductCreatedBy")
                        .WithMany()
                        .HasForeignKey("ProductCreatedByUserID");

                    b.HasOne("UltimateShoppingList.Groups", "ProductSharedWith")
                        .WithMany()
                        .HasForeignKey("ProductSharedWithGroupID");

                    b.HasOne("UltimateShoppingList.ShoppingList", "ShoppingList")
                        .WithMany()
                        .HasForeignKey("ShoppingListID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UltimateShoppingList.ShoppingList", null)
                        .WithMany("ShopListProducts")
                        .HasForeignKey("ShoppingListShopListID");
                });

            modelBuilder.Entity("UltimateShoppingList.ShoppingList", b =>
                {
                    b.HasOne("UltimateShoppingList.Groups", "ShopListUsers")
                        .WithMany()
                        .HasForeignKey("ShopListUsersGroupID");
                });

            modelBuilder.Entity("UltimateShoppingList.User", b =>
                {
                    b.HasOne("UltimateShoppingList.Groups", null)
                        .WithMany("UsersInGroup")
                        .HasForeignKey("GroupsGroupID");
                });
#pragma warning restore 612, 618
        }
    }
}
